const STAT_TITLES = {
  PJ: 'Partidos jugados',
  V: 'Victorias',
  D: 'Derrotas',
  Min: 'Minutos',
  MPP: 'Minutos por partido',
  PPP: 'Puntos por partido',
  Pts: 'Puntos',
  TCA: 'Tiros de campo anotados',
  TCI: 'Tiros de campo intentados',
  'TC%': 'Porcentaje de tiro de campo',
  '2P%': 'Porcentaje de tiro de dos',
  '3PA': 'Triples anotados',
  '3PI': 'Triples intentados',
  '3P%': 'Porcentaje de triple',
  TLA: 'Tiros libres anotados',
  TLI: 'Tiros libres intentados',
  'TL%': 'Porcentaje de tiro libre',
  RO: 'Rebotes ofensivos',
  RD: 'Rebotes defensivos',
  RT: 'Rebotes totales',
  Reb: 'Rebotes',
  RPP: 'Rebotes por partido',
  Ast: 'Asistencias',
  APP: 'Asistencias por partido',
  Rob: 'Robos',
  RBP: 'Robos por partido',
  Tap: 'Tapones',
  TAPP: 'Tapones por partido',
  TPP: 'Tapones por partido',
  'Pér': 'Pérdidas',
  PER: 'Pérdidas por partido',
  Fal: 'Faltas',
  FPP: 'Faltas por partido',
  ORtg: 'Eficiencia ofensiva por 100 posesiones',
  DRtg: 'Eficiencia defensiva por 100 posesiones',
  Neto: 'Eficiencia neta por 100 posesiones',
  Ritmo: 'Posesiones por partido',
  'eFG%': 'Porcentaje de tiro efectivo',
  'TS%': 'True Shooting',
  '3PAr': 'Proporción de tiros de tres',
  'RO%': 'Porcentaje de rebote ofensivo',
  'RD%': 'Porcentaje de rebote defensivo',
  'RT%': 'Porcentaje de rebote total',
  'REB%': 'Porcentaje de rebote total',
  'AST%': 'Porcentaje de asistencias',
  'ROB%': 'Porcentaje de robos',
  'TAP%': 'Porcentaje de tapones',
  'TOV%': 'Porcentaje de pérdidas',
  'PER%': 'Porcentaje de pérdidas',
  'AST/PER': 'Ratio asistencias-pérdidas',
  'USG%': 'Porcentaje de uso',
  TLr: 'Tasa de tiros libres',
  'Pos/PJ': 'Posesiones por partido',
  'Pts Robo%': 'Porcentaje de puntos tras robo',
  '2a Op%': 'Porcentaje de puntos de segunda oportunidad',
  '2da Op%': 'Porcentaje de puntos de segunda oportunidad',
  'Vol. 3P': 'Volumen de tiro de tres',
  '% asistidos': 'Porcentaje de tiros anotados asistidos',
  'Dif. aro': 'Diferencia defensiva en el aro',
  'Dif. 3P': 'Diferencia defensiva en triples',
}

export function statTitle(label) {
  return STAT_TITLES[label] || label
}
